//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Stage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group_Stage()
        {
            this.Team5 = new HashSet<Team>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Place_1 { get; set; }
        public Nullable<int> Place_2 { get; set; }
        public Nullable<int> Place_3 { get; set; }
        public Nullable<int> Place_4 { get; set; }
        public Nullable<int> Place_5 { get; set; }
        public string Abbreviature { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Team Team2 { get; set; }
        public virtual Team Team3 { get; set; }
        public virtual Team Team4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Team5 { get; set; }
    }
}
